### PR TITLE
Using ecmaVersion 8 for acorn

### PR DESCRIPTION
**Pull request by sassanh**
Lets use ecmaVersion 8 just like we did in `bundle-collapser`:

https://github.com/substack/bundle-collapser/commit/5ff52c578ef74d586b5538c85efb27bca7cc2e4d

### CODE REVIEW

**Comment by feross** [comment]
Thoughts on merging this, @goto-bus-stop?

**Comment by goto-bus-stop** [comment]
seems good, i don't have merge powers here though

**Comment by feross** [comment]
@goto-bus-stop I'm sure @substack would give you powers if you pinged him. Also, does this belong in the browserify org?

**Comment by goto-bus-stop** [comment]
yeah exactly, edited in after posting :D

**Comment by goto-bus-stop** [comment]
There it is. thanks @sassanh! I'll bump to acorn@5 then publish a minor version.

**Comment by goto-bus-stop** [comment]
Published! :package: 1.3.0

**Pull request merged**
